# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ba9bd8e3934006c8394af5dbec551f7fde760b061d3bc8d389a553b37a87408302514ae2216372b7795ba44a67f31a31fe12a40b6df5ab65cac817c1e48bf70

test:
  secret_key_base: 97378a5b24cb3fb13e9a278ce17f3f6cfd3116d1c48448f385f819d837ea9d3d7bccf7c28b3e71d2ff665ea94360510cb3e5dc079d6aee8b33e3b4a87b9f1555

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
